language: ruby
cache: bundler
rvm:
  - 2.3.0

before_script:
  - chmod +x ./script/*
  - ./script/setup

script: 
  - ./script/cibuild

deploy:
  provider: script
  script: ./script/rollbar
  on:
    branch: master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
