title: "School Announcements - DEMO"
description: "Demo for School Announcements"
repository: schoolannouncements/schoolannouncements.github.io

exclude: [vendor]

header:
  left-header:
    - text: Home
      internal-link: index.html
    - text: Posts
      internal-link: posts.html
    - text: Documentation
      internal-link: docs/index.html

  right-header:
    - text: Privacy
      internal-link: privacy.html

collections:
  announcements:
    output: true
  sports:
    output: true
  clubs:
    output: true

defaults:
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ""
      type: sports
    values:
      layout: sport
  - scope:
      path: ""
      type: clubs
    values:
      layout: club

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-github-metadata

