title: "Darby Announcements - DEMO"
description: "Demo for Hilliard Darby Announcements"
repository: hcsd-dby/hcsd-dby.github.io

exclude: [vendor]

header:
  left-header:
    - text: Home
      internal-link: index.html
    - text: Posts
      internal-link: posts.html
    - text: Documentation
      internal-link: docs/index.html

  right-header:
    - text: Privacy
      internal-link: privacy.html

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-github-metadata

alert: > 
  Disclaimer: This is not an official web site of the Hilliard City School 
  District or Hilliard Darby High School. The Hilliard City School District 
  or Hilliard Darby High School does not control and cannot guarantee the 
  relevance, timeliness, or accuracy of the information on this web site. 
  Any views or opinions expressed herein are solely those of the creators 
  of this web site. 
