title: "School Announcements - DEMO"
description: "Demo for School Announcements"
repository: schoolnews/schoolnews.github.io
timezone: America/New_York

exclude: [vendor]

collections:
  announcements:
    output: true
    layout: announcement
  sports:
    output: true
    layout: sport
  clubs:
    output: true
    layout: club

defaults:
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ""
      type: sports
    values:
      layout: sport
  - scope:
      path: ""
      type: clubs
    values:
      layout: club

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
