title: "School Announcements - DEMO"
description: "Demo for School Announcements"
repository: schoolnews/schoolnews.github.io
timezone: America/New_York

versions:
  bootstrap: 3.3.6
  font-awesome: 4.6.3
  jquery: 2.2.4
  modernizer: 2.8.3
  autotrack: 1.0.0
  revealjs: 3.3.0
  timeago: 1.5.3

googleanalytics: UA-81210681-1
rollbar: 9af0fe3376854d60a9280e95a374c60a

exclude: [vendor]

header:
  left-header:
    - text: Home
      internal-link: index.html
    - text: Posts
      internal-link: posts.html
    - text: Views
      dropdown:
        - text: All Announcements - Text View
          internal-link: views/text/all.html 
        - text: All Announcements - Slide View
          internal-link: views/slides/all.html 
        - text: Announcements Only - Text View
          internal-link: views/text/announcements.html 
        - text: Announcements Only - Slide View
          internal-link: views/slides/announcements.html 
        - text: Sports Only - Text View
          internal-link: views/text/sports.html 
        - text: Sports Only - Slide View
          internal-link: views/slides/sports.html 
        - text: List View
          internal-link: views/admin.html
        - text: List View - Live
          internal-link: views/admin-live.html 
    - text: Documentation
      internal-link: docs/index.html
  right-header:
    - text: Privacy
      internal-link: privacy.html

collections:
  announcements:
    output: true
    layout: announcement
  sports:
    output: true
    layout: sport
  clubs:
    output: true
    layout: club

defaults:
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ""
      type: sports
    values:
      layout: sport
  - scope:
      path: ""
      type: clubs
    values:
      layout: club

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-paginate

