title: "School Announcements - DEMO"
description: "Demo for School Announcements"
repository: schoolnews/schoolnews.github.io
timezone: America/New_York

googleanalytics: UA-81210681-1
rollbar: 9af0fe3376854d60a9280e95a374c60a

exclude: [vendor]

collections:
  announcements:
    output: true
    layout: announcement
  sports:
    output: true
    layout: sport
  clubs:
    output: true
    layout: club

defaults:
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ""
      type: sports
    values:
      layout: sport
  - scope:
      path: ""
      type: clubs
    values:
      layout: club

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
